/*
 * Copyright © 2019 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package co.cask.gcp.datastore.sink;

import co.cask.cdap.api.data.format.StructuredRecord;
import co.cask.cdap.api.data.schema.Schema;
import co.cask.gcp.datastore.sink.util.SinkKeyType;
import co.cask.gcp.datastore.util.DatastorePropertyUtil;
import com.google.cloud.Timestamp;
import com.google.cloud.datastore.Blob;
import com.google.cloud.datastore.BlobValue;
import com.google.cloud.datastore.BooleanValue;
import com.google.cloud.datastore.DoubleValue;
import com.google.cloud.datastore.EntityValue;
import com.google.cloud.datastore.FullEntity;
import com.google.cloud.datastore.IncompleteKey;
import com.google.cloud.datastore.Key;
import com.google.cloud.datastore.KeyFactory;
import com.google.cloud.datastore.LongValue;
import com.google.cloud.datastore.NullValue;
import com.google.cloud.datastore.PathElement;
import com.google.cloud.datastore.StringValue;
import com.google.cloud.datastore.TimestampValue;
import com.google.cloud.datastore.Value;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.ZonedDateTime;
import java.util.List;
import java.util.Objects;

/**
 * Transforms {@link StructuredRecord} to the Google Cloud Datastore {@link FullEntity}
 * using {@link DatastoreSinkConfig}.
 */
public class DatastoreSinkTransformer {
  private static final Logger LOG = LoggerFactory.getLogger(DatastoreSinkTransformer.class);

  private final DatastoreSinkConfig config;

  public DatastoreSinkTransformer(DatastoreSinkConfig config) {
    this.config = config;
  }

  public FullEntity<?> transformStructuredRecord(StructuredRecord record) {
    KeyFactory keyFactory = new KeyFactory(config.getProject())
      .setNamespace(config.getNamespace())
      .setKind(config.getKind());

    String keyAlias = config.getKeyAlias();
    FullEntity.Builder<IncompleteKey> entityBuilder = FullEntity.newBuilder();
    List<Schema.Field> fields = Objects.requireNonNull(record.getSchema().getFields(), "Schema fields cannot be empty");

    boolean useAutoGeneratedKey = config.shouldUseAutoGeneratedKey();
    for (Schema.Field field : fields) {
      String fieldName = field.getName();
      if (!useAutoGeneratedKey && keyAlias.equals(fieldName)) {
        entityBuilder.setKey(convertToKey(record, keyFactory, field));
      } else {
        boolean excludeFromIndex = isExcludedFromIndex(fieldName);
        entityBuilder.set(fieldName, convertToValue(fieldName, field.getSchema(), record, excludeFromIndex));
      }
    }

    if (useAutoGeneratedKey) {
      entityBuilder.setKey(getAutoGeneratedKey(keyFactory));
    }
    return entityBuilder.build();
  }

  private boolean isExcludedFromIndex(String fieldName) {
    switch (config.getIndexStrategy()) {
      case ALL:
        return false;
      case NONE:
        return true;
      case CUSTOM:
        return !config.getIndexedProperties().contains(fieldName);
      default:
        throw new IllegalStateException(
          String.format("Unsupported index strategy '%s' for field: '%s'", config.getIndexStrategy(), fieldName));
    }
  }

  private IncompleteKey getAutoGeneratedKey(KeyFactory keyFactory) {
    List<PathElement> ancestors = config.getAncestor();
    if (!ancestors.isEmpty()) {
      keyFactory.addAncestors(ancestors);
    }
    return keyFactory.newKey();
  }

  @SuppressWarnings("ConstantConditions")
  private IncompleteKey convertToKey(StructuredRecord record, KeyFactory keyFactory, Schema.Field field) {
    Schema.Type schemaType = field.getSchema().getType();
    SinkKeyType keyType = config.getKeyType();
    switch (schemaType) {
      case STRING: {
        String strValue = record.get(field.getName());
        if (strValue.isEmpty()) {
          throw new IllegalStateException(
            String.format("Key value cannot be empty. Key field: '%s', Key type: '%s'", field.getName(),
                          keyType.getValue()));
        }
        switch (keyType) {
          case CUSTOM_NAME: {
            List<PathElement> ancestors = config.getAncestor();
            if (!ancestors.isEmpty()) {
              keyFactory.addAncestors(ancestors);
            }
            return keyFactory.newKey(strValue);
          }
          case KEY_LITERAL: {
            return transformKeyLiteralToKey(field, keyFactory, strValue);
          }
          case URL_SAFE_KEY:
            return transformToUrlSafeKey(field, keyType, strValue);
          default:
            throw new IllegalStateException(
              String.format("Field '%s' of type '%s' cannot be used as a Cloud Datastore key type '%s'",
                            field.getName(), schemaType, keyType.getValue()));
        }
      }
      case INT:
      case LONG: {
        switch (keyType) {
          case CUSTOM_NAME: {
            List<PathElement> ancestors = config.getAncestor();
            if (!ancestors.isEmpty()) {
              keyFactory.addAncestors(ancestors);
            }
            Number numValue = record.get(field.getName());
            return keyFactory.newKey(numValue.longValue());
          }
          default:
            throw new IllegalStateException(
              String.format("Key field '%s' of type '%s' is not supported for record type: '%s'",
                            field.getName(), keyType.getValue(), schemaType));
        }
      }
      default:
        String foundType = field.getSchema().isNullable()
          ? "nullable " + field.getSchema().getNonNullable().getType().name()
          : schemaType.name();
        throw new IllegalStateException(
          String.format("Key field '%s' of type '%s' is not supported by key type: '%s'",
                        field.getName(), foundType, keyType.getValue()));
    }
  }

  /**
   * Transforms Url-safe key string to Google Cloud Datastore Key.
   * Url-safe key will represented in the encoded form that can be used as part of a URL.
   * For example: partition_id+%7B%0A++project_id%3A+%22test-project%22%0A++namespace_id%3A+% ...
   * <p/>
   * Note: Defined Project, Namespace, Kind must match extracted Project, Namespace, Kind accordingly.
   *
   * @param field      schema field with key value
   * @param keyType    type of key assigned to entities
   * @param urlSafeKey Url-safe key string
   * @return complete Google Cloud Datastore Key
   */
  private Key transformToUrlSafeKey(Schema.Field field, SinkKeyType keyType, String urlSafeKey) {
    Key key = Key.fromUrlSafe(urlSafeKey);
    if (!Objects.equals(config.getProject(), key.getProjectId())) {
      throw new IllegalArgumentException(
        String.format("%s projectId must be equal to defined projectId. Key field: '%s', " +
                        "Expected: '%s', Received: '%s'",
                      keyType.getValue(), field.getName(), config.getProject(), key.getProjectId()));
    } else if (!Objects.equals(config.getNamespace(), key.getNamespace())) {
      throw new IllegalArgumentException(
        String.format("%s namespace must be equal to defined namespace. Key field: '%s', " +
                        "Expected: '%s', Received: '%s'",
                      keyType.getValue(), field.getName(), config.getNamespace(), key.getNamespace()));
    } else if (!Objects.equals(config.getKind(), key.getKind())) {
      throw new IllegalArgumentException(
        String.format("%s kind must be equal to defined kind. Key field: '%s', " +
                        "Expected: '%s', Received: '%s'",
                      keyType.getValue(), field.getName(), config.getKind(), key.getKind()));
    }
    return key;
  }

  /**
   * Transforms Key Literal string to Google Cloud Datastore Key.
   * Key Literal string format: <i>key(kind_1, identifier_1, kind_2, identifier_2, [...])</i>.
   * <p/>
   * Example of key literal string: <i>"key(kind_1, 'stringId', kind_2, 100)"</i>
   * <p/>
   * Extracted kind: <i>kind_2</i>
   * <br/>
   * Extracted identifier: <i>100</i>
   * <br/>
   * Extracted Ancestor: <i>key(kind_1, 'stringId')</i>
   * <p/>
   * Note: Kind set to KeyFactory must match extracted Kind.
   *
   * @param field      schema field with key value
   * @param keyFactory Key creation factory
   * @param keyLiteral Key Literal string
   * @return complete Google Cloud Datastore Key
   */
  private Key transformKeyLiteralToKey(Schema.Field field, KeyFactory keyFactory, String keyLiteral) {
    List<PathElement> pathElements = DatastorePropertyUtil.parseKeyLiteral(keyLiteral);
    LOG.trace("Key Literal '{}' path elements: {}", keyLiteral, pathElements);
    if (pathElements.isEmpty()) {
      throw new IllegalArgumentException(String.format("Field '%s' value has unexpected Key Literal format: '%s'",
                                                       field.getName(), keyLiteral));
    }

    PathElement keyElement = pathElements.get(pathElements.size() - 1);
    LOG.trace("Detected keyElement: '{}'", keyElement);
    if (!config.getKind().equals(keyElement.getKind())) {
      throw new IllegalArgumentException(
        String.format("Received Key Literal kind '%s' must match defined kind '%s'. Field '%s', key literal: '%s'",
                      keyElement.getKind(), config.getKind(), field.getName(), keyLiteral));
    }

    List<PathElement> ancestors = pathElements.subList(0, pathElements.size() - 1);
    if (!ancestors.isEmpty()) {
      LOG.trace("Detected ancestors: {}", ancestors);
      keyFactory.addAncestors(ancestors);
    }

    if (keyElement.hasId()) {
      return keyFactory.newKey(keyElement.getId());
    }
    return keyFactory.newKey(keyElement.getName());
  }

  @SuppressWarnings("ConstantConditions")
  private Value<?> convertToValue(String fieldName, Schema fieldSchema, StructuredRecord record,
                                  boolean excludeFromIndex) {
    if (record.get(fieldName) == null) {
      return NullValue.newBuilder()
        .setExcludeFromIndexes(excludeFromIndex)
        .build();
    }

    Value<?> outValue;
    Schema.LogicalType logicalType = fieldSchema.getLogicalType();
    if (logicalType != null) {
      switch (logicalType) {
        case TIMESTAMP_MILLIS:
        case TIMESTAMP_MICROS:
          ZonedDateTime ts = record.getTimestamp(fieldName);
          Timestamp gcpTimestamp = Timestamp.ofTimeSecondsAndNanos(ts.toEpochSecond(), ts.getNano());
          outValue = TimestampValue.newBuilder(gcpTimestamp)
            .setExcludeFromIndexes(excludeFromIndex)
            .build();
          return outValue;
        default:
          throw new IllegalStateException(
            String.format("Record type '%s' is not supported for field '%s'", logicalType.getToken(), fieldName));
      }
    }

    switch (fieldSchema.getType()) {
      case STRING:
        outValue = StringValue.newBuilder(record.get(fieldName))
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case INT:
      case LONG:
        Number longValue = record.get(fieldName);
        outValue = LongValue.newBuilder(longValue.longValue())
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case FLOAT:
      case DOUBLE:
        Number doubleValue = record.get(fieldName);
        outValue = DoubleValue.newBuilder(doubleValue.doubleValue())
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case BOOLEAN:
        outValue = BooleanValue.newBuilder(record.get(fieldName))
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case BYTES:
        byte[] byteArray = record.get(fieldName);
        outValue = BlobValue.newBuilder(Blob.copyFrom(byteArray))
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case RECORD:
        StructuredRecord nestedRecord = record.get(fieldName);
        FullEntity.Builder<IncompleteKey> nestedBuilder = FullEntity.newBuilder();
        Objects.requireNonNull(fieldSchema.getFields(), "Nested Schema fields cannot be empty").forEach(
          nestedField -> nestedBuilder.set(nestedField.getName(),
                                           convertToValue(nestedField.getName(), nestedField.getSchema(),
                                                          nestedRecord, excludeFromIndex)));
        outValue = EntityValue.newBuilder(nestedBuilder.build())
          .setExcludeFromIndexes(excludeFromIndex)
          .build();
        break;
      case UNION:
        if (fieldSchema.isNullable()) {
          outValue = convertToValue(fieldName, fieldSchema.getNonNullable(), record, excludeFromIndex);
          break;
        }
        throw new IllegalStateException(
          String.format("Record type 'complex UNION' for field '%s'", fieldName));
      default:
        throw new IllegalStateException(
          String.format("Record type '%s' is not supported for field '%s'", fieldSchema.getType().name(), fieldName));
    }
    return outValue;
  }
}
