/*
 * Copyright © 2020 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package io.cdap.plugin.gcp.firestore.sink.util;

import java.util.Arrays;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Indicates id type which will be used when inserting / upserting Firestore document.
 */
public enum SinkIdType {

  /**
   * Key will be automatically generated by the Firestore in a form of alpha-numeric ID.
   */
  AUTO_GENERATED_ID("Auto-generated id"),

  /**
   * Key will be constructed using custom name or alpha-numeric ID.
   */
  CUSTOM_NAME("Custom name");

  private final String value;

  SinkIdType(String value) {
    this.value = value;
  }

  /**
   * Converts id type string value into {@link SinkIdType} enum.
   *
   * @param stringValue id type string value
   * @return sink id type in optional container
   */
  public static Optional<SinkIdType> fromValue(String stringValue) {
    return Stream.of(values())
      .filter(keyType -> keyType.value.equalsIgnoreCase(stringValue))
      .findAny();
  }

  public static String getSupportedTypes() {
    return Arrays.stream(SinkIdType.values()).map(SinkIdType::getValue).collect(Collectors.joining(", "));
  }

  public String getValue() {
    return value;
  }
}
