/*
 * Copyright © 2020 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package io.cdap.plugin.gcp.firestore.sink;

import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.WriteBatch;
import com.google.cloud.firestore.WriteResult;
import com.google.common.base.Strings;
import io.cdap.plugin.gcp.common.GCPConfig;
import io.cdap.plugin.gcp.firestore.sink.util.FirestoreSinkConstants;
import io.cdap.plugin.gcp.firestore.util.FirestoreConstants;
import io.cdap.plugin.gcp.firestore.util.FirestoreUtil;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.io.NullWritable;
import org.apache.hadoop.mapreduce.RecordWriter;
import org.apache.hadoop.mapreduce.TaskAttemptContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * {@link FirestoreRecordWriter} writes the job outputs to the Firestore.
 */
public class FirestoreRecordWriter extends RecordWriter<NullWritable, Map<String, Object>> {
  private static final Logger LOG = LoggerFactory.getLogger(FirestoreRecordWriter.class);

  private final Firestore db;
  private final int batchSize;
  private final boolean useAutogeneratedId;
  private WriteBatch batch;
  private int totalCount;
  private int numberOfRecordsInBatch;
  private CollectionReference collectionRef;

  /**
   * Constructor for FirestoreRecordWriter object.
   * @param taskAttemptContext the task attempt context
   */
  public FirestoreRecordWriter(TaskAttemptContext taskAttemptContext) {
    Configuration config = taskAttemptContext.getConfiguration();
    String projectId = config.get(GCPConfig.NAME_PROJECT);
    String serviceAccountFilePath = config.get(GCPConfig.NAME_SERVICE_ACCOUNT_FILE_PATH);
    String databaseId = config.get(FirestoreConstants.PROPERTY_DATABASE_ID);
    String collection = Strings.nullToEmpty(config.get(FirestoreConstants.PROPERTY_COLLECTION)).trim();
    this.batchSize = config.getInt(FirestoreSinkConstants.PROPERTY_BATCH_SIZE, 25);
    this.useAutogeneratedId = config.getBoolean(FirestoreSinkConstants.PROPERTY_ID_TYPE, false);
    LOG.debug("Initialize RecordWriter(projectId={}, database={}, collection={}, serviceFilePath={}, batchSize={}, " +
        "useAutogeneratedId={})", projectId, databaseId, collection, serviceAccountFilePath, batchSize,
      useAutogeneratedId);

    this.db = FirestoreUtil.getFirestore(serviceAccountFilePath, projectId, databaseId);
    this.collectionRef = db.collection(collection);
    this.batch = db.batch();
    this.totalCount = 0;
    this.numberOfRecordsInBatch = 0;
  }

  @Override
  public void write(NullWritable key, Map<String, Object> entity) throws IOException, InterruptedException {
    LOG.trace("RecordWriter write({})", entity);

    DocumentReference docRef = null;
    if (!useAutogeneratedId && entity.containsKey(FirestoreConstants.ID_PROPERTY_NAME)) {
      String documentId = (String) entity.remove(FirestoreConstants.ID_PROPERTY_NAME);
      docRef = collectionRef.document(documentId);
    } else {
      docRef = collectionRef.document();
    }

    batch.set(docRef, entity);

    ++totalCount;
    ++numberOfRecordsInBatch;
    if (totalCount % batchSize == 0) {
      flush();
    }
  }

  @Override
  public void close(TaskAttemptContext taskAttemptContext) throws IOException, InterruptedException {
    flush();
    try {
      db.close();
    } catch (Exception e) {
      throw new IOException(e.getMessage(), e);
    }
    LOG.debug("Total number of values written to Cloud Firestore: {}", totalCount);
  }

  private void flush() throws InterruptedException {
    if (numberOfRecordsInBatch > 0) {
      LOG.debug("Writing a batch of {} values to Cloud Firestore.", numberOfRecordsInBatch);
      try {
        ApiFuture<List<WriteResult>> result = batch.commit();
        result.get();
        batch = db.batch();
        numberOfRecordsInBatch = 0;
      } catch (Exception e) {
        LOG.error("Error while executing batch: ", e);
        throw new InterruptedException(e.getMessage());
      }
    }
  }
}
