/*
 * Copyright © 2019 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.cdap.plugin.gcp.datastore.sink.util;

/**
 * Datastore Sink constants.
 */
public interface DatastoreSinkConstants {

  String PROPERTY_SERVICE_FILE_PATH = "serviceFilePath";
  String PROPERTY_PROJECT = "project";
  String PROPERTY_NAMESPACE = "namespace";
  String PROPERTY_KIND = "kind";
  String PROPERTY_KEY_TYPE = "keyType";
  String PROPERTY_KEY_ALIAS = "keyAlias";
  String PROPERTY_INDEX_STRATEGY = "indexStrategy";
  String PROPERTY_ANCESTOR = "ancestor";
  String PROPERTY_BATCH_SIZE = "batchSize";
  String PROPERTY_INDEXED_PROPERTIES = "indexedProperties";

  String CONFIG_PROJECT = "mapred.gcd.output.project";
  String CONFIG_USE_AUTOGENERATED_KEY = "mapred.gcd.output.use.autogenerated.key";
  String CONFIG_BATCH_SIZE = "mapred.gcd.output.batch.size";
  String CONFIG_SERVICE_ACCOUNT_FILE_PATH = "mapred.gcd.output.service.account.file.path";

  // Maximum number of entities that can be passed to a Commit operation in the Cloud Datastore API
  int MAX_BATCH_SIZE = 500;
}
