# Copyright © 2021 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Note: Any changes to this workflow would be used only after merging into develop
name: Build with unit tests

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build:
    name: 'build'
    runs-on: k8s-runner-build

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ inputs.ref }}
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ github.workflow }}
    - name: Build with Maven
      run: mvn clean test -fae -T 2 -B -V -DcloudBuild -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2.2.2
      if: always()
      with:
        name: Build debug files
        path: |
          **/target/rat.txt
          **/target/surefire-reports/*
    - name: Surefire Report
      # Pinned 1.0.5 version
      uses: ScaCap/action-surefire-report@ad808943e6bfbd2e6acba7c53fdb5c89534da533
      if: always()
      with:
        # GITHUB_TOKEN
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ inputs.ref }}